import Head from 'next/head'

interface LayoutProps {
  children: React.ReactNode
}

export interface CommonProps {
  extraStyle?: string
}

export const Layout = ({ children }: LayoutProps) => (
  <>
    <Head>
      <title>Leninner | Learning everytime</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="scroll-smooth w-full">{children}</main>
  </>
)
