import Head from 'next/head'
import { StepBlog } from '../modules/StepBlog'
import { StepIntroduction } from '../modules/StepIntroduction'

const Home = () => (
  <>
    <Head>
      <title>Leninner | Learning everytime</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <StepIntroduction />
    <StepBlog />
    <StepIntroduction />
  </>
)

export default Home
